name: 'Git User Random GPG Key'
description: 'Add a randomly generated GPG key to the git user'
author: Jan-Hendrik Ewers
branding:
  icon: chevron-up
  color: yellow

inputs:
  email:
    description: 'Email associated with the user'
    required: true
  name:
    description: 'Name of the user'
    required: true
outputs:
  gpg_key_id:
    description: "The long form GPG key ID"
    value: ${{ steps.gpg_key_id.outputs.gpg_key_id }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: run.sh ${{ inputs.email }} ${{ inputs.email }}
      shell: bash
    - id: gpg_key_id
      run: echo "::set-output name=gpg_key_id::$(git config --global user.signingkey)"
      shell: bash
